{
 "title": "Geofox cluster - Prometheus",
 "description": "Postgres-XL cluster stats using node_exporter.\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "cluster", "label": "cluster", "query": "label_values(cluster)" }
  ]
 },
 "panels": [
  { "title": "Node Statistics (NodeExporter)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"})-sum(node_memory_Active_bytes{cluster=\"$cluster\"}))/(sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_anon_bytes{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(node_memory_Active_anon_bytes{cluster='$cluster'})",
     "legendFormat": "Cluster Memory Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_Active_bytes{cluster='$cluster'})"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by(instance)(irate(node_cpu_seconds_total{job='prometheus_consul_node',cluster='$cluster', mode!=\"idle\"}[$interval])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_disk_read_bytes_total{cluster='$cluster'}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_disk_written_bytes_total{cluster='$cluster'}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Space in root filesystem",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{cluster=\"$cluster\", mountpoint='/', device != 'rootfs'})*100 / (node_filesystem_size_bytes{cluster=\"$cluster\", mountpoint='/', device != 'rootfs'})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}